# Generated by Django 3.1.7 on 2021-03-08 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_auto_20210307_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='total_user',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
    ]
