# Generated by Django 3.1.7 on 2021-03-07 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_apply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='apply',
        ),
    ]
